-- ============================================
-- Morateur 2026 — Données initiales (seed)
-- ============================================

-- Articles / Actualités
INSERT INTO articles (title, date, image, tag, description, sort_order) VALUES
('Lancement officiel de la campagne', '15 Janvier 2026', 'https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?w=800&h=500&fit=crop', 'Événement', 'Le coup d''envoi de notre aventure collective pour redonner à Bouc-Bel-Air le dynamisme qu''elle mérite.', 1),
('Rencontre avec les commerçants du centre-ville', '28 Janvier 2026', 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=800&h=500&fit=crop', 'Terrain', 'Échanges concrets avec les commerçants sur la revitalisation du centre ancien et les aides à l''installation.', 2),
('Réunion publique : urbanisme et cadre de vie', '5 Février 2026', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop', 'Programme', 'Présentation de nos mesures contre les promoteurs et pour un urbanisme maîtrisé.', 3),
('Porte-à-porte dans le quartier des Music', '12 Février 2026', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=500&fit=crop', 'Terrain', 'À la rencontre des habitants, quartier par quartier, pour écouter et comprendre vos besoins.', 4),
('Tribune : Protégeons nos espaces naturels', '20 Février 2026', 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=500&fit=crop', 'Tribune', 'Un appel à la préservation des collines et espaces boisés face à la pression immobilière.', 5);

-- Programme : Piliers
INSERT INTO programme_pillars (id, title, intro, icon, color, icon_bg, sort_order) VALUES
('a1000000-0000-0000-0000-000000000001', 'Faire barrage aux promoteurs', 'Notre commune se trouve à un tournant. En moins d''un an, des permis pour plus de 1000 logements ont été déposés. Il est temps d''agir.', 'ShieldCheck', 'border-campaign-lime/30', 'gradient-lime', 1),
('a1000000-0000-0000-0000-000000000002', 'Des infrastructures à la hauteur', 'La vétusté de nos bâtiments publics est indigne de notre commune. Écoles, crèches, voiries : tout doit être remis à niveau.', 'Building2', 'border-campaign-steel/30', 'gradient-teal', 2),
('a1000000-0000-0000-0000-000000000003', 'Revitaliser le village', 'Notre centre ancien a tant à offrir. Retrouver son âme, ramener la vie dans ses ruelles pittoresques : c''est notre priorité.', 'Store', 'border-campaign-olive/30', 'bg-campaign-olive', 3);

-- Programme : Mesures
INSERT INTO programme_measures (pillar_id, title, detail, sort_order) VALUES
-- Pilier 1 : Faire barrage aux promoteurs
('a1000000-0000-0000-0000-000000000001', 'Refus systématique des permis de construire des promoteurs', 'Nous refuserons systématiquement les permis de construire demandés par les promoteurs immobiliers afin de les forcer à la négociation et protéger le cadre de vie des Boucains.', 1),
('a1000000-0000-0000-0000-000000000001', 'Droit de préemption urbain', 'Utilisation systématique du droit de préemption urbain pour permettre la création de logements sociaux adaptés à notre commune, sans laisser le champ libre aux promoteurs.', 2),
('a1000000-0000-0000-0000-000000000001', 'Soutien aux recours des riverains', 'Nous soutiendrons activement les recours intentés par les riverains sur les permis existants, en leur apportant un accompagnement juridique et technique.', 3),
('a1000000-0000-0000-0000-000000000001', 'Bail réel solidaire', 'Recours au bail réel solidaire pour l''intégralité des projets collectifs afin de limiter les constructions spéculatives et de privilégier les parcours résidentiels des Boucains.', 4),
-- Pilier 2 : Des infrastructures à la hauteur
('a1000000-0000-0000-0000-000000000002', 'Rénovation des bâtiments municipaux', 'Réaliser la rénovation complète de l''ensemble des bâtiments municipaux, y compris le foyer des Anciens, pour offrir des conditions dignes à tous les usagers.', 1),
('a1000000-0000-0000-0000-000000000002', 'Climatisation dans les écoles et crèches', 'Installer la climatisation réversible dans toutes les crèches, toutes les écoles et au foyer des anciens. Il est inacceptable que le thermomètre dépasse 30°C dès mai dans certaines écoles.', 2),
('a1000000-0000-0000-0000-000000000002', 'Requalification des axes routiers', 'Requalifier et renouveler les principaux axes de notre commune : avenue Thiers, avenue de la Mounine, avenue Beausoleil, chemin de Sauvecanne… et la RD8n.', 3),
('a1000000-0000-0000-0000-000000000002', 'Échangeurs autoroutiers', 'Lancer les études sur l''aménagement des échangeurs autoroutiers des Trois Pigeons et des Chabauds, afin de présenter un projet solide à l''État.', 4),
-- Pilier 3 : Revitaliser le village
('a1000000-0000-0000-0000-000000000003', 'Centre ancien attractif', 'Faire de notre centre ancien un lieu attractif pour l''ensemble des habitants, en s''appuyant sur son caractère unique, son histoire et son patrimoine architectural.', 1),
('a1000000-0000-0000-0000-000000000003', 'Animations et vie culturelle', 'Étendre les animations au-delà de la place principale, dans les ruelles pittoresques du centre ancien. Retrouver l''esprit des retraites aux flambeaux et des fêtes de village.', 2),
('a1000000-0000-0000-0000-000000000003', 'Incubateur commercial et artisanal', 'Créer un incubateur d''entreprises de restauration et de savoir-faire artisanaux pour redonner vie au commerce local et attirer de nouveaux talents.', 3),
('a1000000-0000-0000-0000-000000000003', 'Offre commerciale renouvelée', 'Développer une offre commerciale de proximité diversifiée, en accompagnant les porteurs de projets et en facilitant l''installation de nouveaux commerces dans le centre-ville.', 4);

-- Événements / Roadmap
INSERT INTO events (icon, date, title, description, is_done, sort_order) VALUES
('Megaphone', 'Janvier 2026', 'Lancement de la campagne', 'Présentation officielle de la liste et du programme.', true, 1),
('Users', 'Février 2026', 'Rencontres de terrain', 'Porte-à-porte, réunions publiques dans tous les quartiers.', true, 2),
('Flag', 'Mars 2026', 'Meetings publics', 'Grands rassemblements thématiques sur les 3 piliers du programme.', false, 3),
('CalendarCheck', 'Mars 2026', '1ᵉʳ tour', 'Jour de vote – chaque voix compte pour l''avenir de notre commune.', false, 4),
('Vote', 'Mars 2026', '2ᵉ tour', 'Mobilisation générale pour confirmer le choix du renouveau.', false, 5),
('PartyPopper', 'Avril 2026', 'Installation du conseil', 'Mise en œuvre immédiate des premières mesures du programme.', false, 6);

-- Membres de l'équipe
INSERT INTO team_members (name, role, image, description, sort_order) VALUES
('Manon Clément-Costa', 'Cheffe d''entreprise', '/images/equipe-1.png', 'Entrepreneure engagée, elle met son expérience de la gestion et de l''innovation au service du territoire.', 1),
('Jean-Luc Berger', 'Responsable financier', '/images/equipe-2.png', 'Expert en finances publiques, garant d''une gestion rigoureuse et transparente des budgets communaux.', 2),
('Valérie Castineiras', 'RH & Pompier volontaire', '/images/equipe-3.png', 'Professionnelle des ressources humaines et pompier volontaire, elle incarne l''engagement citoyen au quotidien.', 3),
('François Deniau', 'Dir. commercial retraité', '/images/equipe-4.png', 'Fort de 30 ans d''expérience, il apporte sa vision stratégique et son ancrage local.', 4);

-- Articles de presse
INSERT INTO press_articles (source, author, date, title, excerpt, url, logo, sort_order) VALUES
('La Marseillaise', 'Eva Bonnet-Gonnet', '24 Décembre 2025', 'Mathieu Morateur revient comme candidat', 'Après une première expérience municipale, Mathieu Morateur annonce son retour sur la scène politique locale de Bouc-Bel-Air avec l''ambition de proposer une alternative crédible aux habitants.', 'https://www.lamarseillaise.fr/accueil/mathieu-morateur-revient-comme-candidat-ON19366109', '/images/logo-lamarseillaise.svg', 1),
('La Provence', 'Carole Barletta', '25 Octobre 2025', 'Municipales 2026 à Bouc-Bel-Air : Mathieu Morateur veut faire barrage aux promoteurs', 'Le candidat aux municipales de 2026 à Bouc-Bel-Air affirme sa volonté de protéger le cadre de vie des Boucains face à la pression immobilière et aux projets des promoteurs.', 'https://www.laprovence.com/article/elections/1485411779646614/municipales-2026-a-bouc-bel-air-mathieu-morateur-se-veut-faire-barrage-aux-promoteurs', '/images/logo-laprovence.svg', 2);

-- Pages SEO
INSERT INTO seo_pages (path, title, description, keywords, og_image) VALUES
('/', 'Morateur 2026 — Bouc Bel Air a de l''Avenir', 'Mathieu Morateur, candidat aux élections municipales 2026 à Bouc-Bel-Air. Découvrez le programme et l''équipe.', 'Morateur 2026, Mathieu Morateur, municipales 2026, Bouc-Bel-Air, élections municipales, candidat maire', '/images/candidat-banner.png'),
('/candidat', 'Le Candidat | Morateur 2026', 'Découvrez le parcours et les engagements de Mathieu Morateur, candidat aux municipales 2026 à Bouc-Bel-Air.', 'Mathieu Morateur, candidat, parcours, engagements, Bouc-Bel-Air', '/images/candidat-banner.png'),
('/programme', 'Le Programme | Morateur 2026', 'Trois piliers concrets pour redonner à Bouc-Bel-Air le cadre de vie qu''elle mérite. Urbanisme, infrastructures, village.', 'programme municipal, urbanisme, infrastructures, village, Bouc-Bel-Air', '/images/candidat-banner.png'),
('/actualites', 'Actualités | Morateur 2026', 'Suivez notre campagne au quotidien, sur le terrain et auprès des Boucains.', 'actualités, campagne, terrain, Bouc-Bel-Air, municipales', '/images/candidat-banner.png'),
('/equipe', 'L''Équipe | Morateur 2026', 'Découvrez l''équipe qui porte le projet Morateur 2026 pour Bouc-Bel-Air.', 'équipe, liste municipale, candidats, Bouc-Bel-Air', '/images/equipe-groupe.png'),
('/presse', 'Presse | Morateur 2026', 'Retrouvez les articles de presse consacrés à notre campagne pour Bouc-Bel-Air.', 'presse, médias, articles, La Provence, La Marseillaise, Bouc-Bel-Air', '/images/candidat-banner.png'),
('/quartiers', 'Consultations par quartier | Morateur 2026', 'Donnez votre avis sur l''avenir de votre quartier à Bouc-Bel-Air. Participez aux consultations citoyennes.', 'consultations, quartiers, Bouc-Bel-Air, citoyens, avis', '/images/candidat-banner.png');

-- ============================================
-- Quartiers & Questions de consultation
-- ============================================

INSERT INTO quartiers (slug, name, description, is_active, display_order) VALUES
  ('roumanille', 'Roumanille-Thiers', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 1),
  ('bergerie', 'La Bergerie', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 2),
  ('mounine', 'La Mounine', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 3),
  ('chabauds-malle-pin', 'Chabauds-Malle-Pin', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 4),
  ('salle', 'La Salle', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 5),
  ('violesiroussin', 'Violesi - San Baquis', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 6),
  ('centreville', 'Centre Ville', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 7),
  ('revenants', 'Les Revenants', 'Merci à vous de prendre le temps de répondre aux questions suivantes. Vos réponses nous aideront à mieux comprendre vos attentes.', true, 8),
  ('gratiane', 'Gratiane', 'Formulaire à venir.', false, 9),
  ('montaury', 'Montaury', 'Formulaire à venir.', false, 10);

-- Questions : Roumanille-Thiers
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'roumanille'), 1, 'La circulation, tant des voitures que des poids lourds, asphyxie notre quartier. Quelles sont à votre avis les mesures immédiates à prendre pour limiter les nuisances de ce trafic sur votre vie quotidienne ?'),
  ((SELECT id FROM quartiers WHERE slug = 'roumanille'), 2, 'Une orientation d''aménagement programmé a été inscrite au Plan local d''urbanisme intercommunal du 5 décembre 2024, à la demande de la mairie, au lieu-dit Leï Morts. Elle prévoit 150 logements, avec une voie de desserte à sens unique depuis l''avenue Thiers, au niveau de la rue du Petit Lac, débouchant sur le chemin Joseph de Roumanille. Ce projet prend place sur des terrains très régulièrement inondés. Souhaitez-vous que cette orientation d''aménagement programmée soit :'),
  ((SELECT id FROM quartiers WHERE slug = 'roumanille'), 3, 'La requalification de l''Avenue Thiers, préparée en 2019 et budgétisée dès 2020, est à l''arrêt depuis 5 ans. En cause, la décision de ne pas toucher à l''alignement des pins parasol la bordant. Que proposez-vous pour relancer ce projet ?');

-- Questions : La Bergerie
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'bergerie'), 1, 'La circulation automobile asphyxie notre quartier. Et nous devons prévoir, en plus des nuisances de l''IBS, l''afflux de nouveaux habitants à Bel-Ombre sous quelques semaines. Quelles sont à votre avis les mesures immédiates à prendre pour limiter les nuisances de ce trafic sur votre vie quotidienne ?'),
  ((SELECT id FROM quartiers WHERE slug = 'bergerie'), 2, 'Les chemins de la Tuilerie et de Valabre notamment ne sont pas reliés aux réseaux d''adduction d''eau potable et d''assainissement collectif. Des projets d''extension existent. Pensez-vous qu''ils doivent être priorisés ?'),
  ((SELECT id FROM quartiers WHERE slug = 'bergerie'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?'),
  ((SELECT id FROM quartiers WHERE slug = 'bergerie'), 4, 'L''avenue Beausoleil concentre les flux de voitures venant du quartier. Il est à présent possible d''y créer une voie verte et des feux de circulation intelligents. Quelles seraient vos suggestions à ce sujet ?');

-- Questions : La Mounine
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'mounine'), 1, 'La circulation automobile asphyxie notre quartier. Et nous devons prévoir, en plus des nuisances actuelles, l''afflux de nouveaux habitants à Bel-Ombre sous quelques semaines. Quelles sont à votre avis les mesures immédiates à prendre pour limiter les nuisances de ce trafic sur votre vie quotidienne ?'),
  ((SELECT id FROM quartiers WHERE slug = 'mounine'), 2, 'Les voies de l''avenue Maréchal de Lattre de Tassigny et la place formée par l''avenue Maréchal Leclerc doivent impérativement être refaites. Il est absolument nécessaire d''intégrer à ce projet les travaux de raccordement à l''eau potable du lotissement Rhin et Danube. De plus, un risque d''inondation existe dans le quartier et la place Maréchal Leclerc sert de bassin de rétention des eaux de pluie. Pensez-vous comme nous que ce projet d''ensemble doit être priorisé à l''échelle de la commune ?'),
  ((SELECT id FROM quartiers WHERE slug = 'mounine'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?'),
  ((SELECT id FROM quartiers WHERE slug = 'mounine'), 4, 'L''avenue de la Mounine concentre les flux de voitures venant du quartier. Il est à présent possible d''y créer une voie verte et de rendre les feux de circulation intelligents, notamment de les activer uniquement si le nombre de véhicules l''impose. Quelles seraient vos suggestions à ce sujet ?');

-- Questions : Chabauds-Malle-Pin
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'chabauds-malle-pin'), 1, 'Le camping de la Malle est destiné, d''après le plan local d''urbanisme, à être remplacé par un immense projet immobilier de 400 logements, en plus bureaux. Les routes et l''ensemble des réseaux publics du quartier ne sont pas du tout adaptés à une population de cette ampleur ! Aussi, nous estimons que nous devons ramener ce projet à une taille plus raisonnable d''environ 200 logements, s''ils étaient tous réalisés en accession sociale à la propriété, cela pourrait couvrir plus de 3 ans d''obligations de création de logements sociaux pour l''ensemble de la commune.'),
  ((SELECT id FROM quartiers WHERE slug = 'chabauds-malle-pin'), 2, 'Le permis de construire du datacenter a été octroyé le 22 janvier par Mathieu Pietri, se faisant la mairie se retrouve sans argument pour imposer d''éventuelles adaptations de nature à protéger les riverains des nuisances. Nous refuserons ce permis, qui est frappé d''illégalité puisque les projets de cette puissance installée doivent prévoir depuis le 1er octobre un dispositif de valorisation de la chaleur, ce que le datacenter MRS6 ne fait pas.'),
  ((SELECT id FROM quartiers WHERE slug = 'chabauds-malle-pin'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?'),
  ((SELECT id FROM quartiers WHERE slug = 'chabauds-malle-pin'), 4, 'Nous estimons que la collectivité doit s''engager à un programme de lutte contre les nuisibles fort et clair, comprenant des mesures actives dans l''espace public comme la pose de pièges à rats et d''aspirateurs à moustiques, un accompagnement des mesures individuelles dans le jardin avec des tarifs négociés pour les dispositifs à placer dans les jardins, et des mesures coercitives lorsque les habitants laissent s''installer des troubles à la salubrité (eaux stagnantes permettant la prolifération de moustiques et ordures dans les jardins permettant celles des rats).');

-- Questions : La Salle
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'salle'), 1, 'La bétonnisation, entérinée par le plan local d''urbanisme approuvé par la municipalité sortante, est en passe de toucher le quartier de la Salle au niveau des champs cultivés de Castel Régina. Ce projet, appelé La Salle Ouest, prévoit 70 logements. Il fait partie des projets que nous pourrons supprimer, car nous imposerons sur la commune une règle simple : afin de limiter la construction de nouveaux logements au nombre strictement nécessaire pour atteindre les objectifs de création de logements sociaux (170 tous les 3 ans), tous les projets immobiliers collectifs seront proposés en bail réel solidaire, c''est-à-dire en accession sociale à la propriété (et non en locatif social). Pour produire ces 170 logements en 3 ans, plutôt que les 1000 aujourd''hui projetés, ce projet de Castel Régina n''est pas nécessaire, ni aujourd''hui, ni d''ici les 2 prochains mandats. Aussi nous le supprimerons. Qu''en pensez-vous ?'),
  ((SELECT id FROM quartiers WHERE slug = 'salle'), 2, 'Le centre commercial de la Salle sera revitalisé par une politique d''animation commerciale portée par la municipalité, avec animations saisonnières véhiculées notamment par la future application de la mairie.'),
  ((SELECT id FROM quartiers WHERE slug = 'salle'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?'),
  ((SELECT id FROM quartiers WHERE slug = 'salle'), 4, 'La lutte contre la prolifération des moustiques dans le quartier passe par le traitement des berges du vallat chaque printemps, et par la pose et la maintenance de bornes aspirateurs à moustiques autour des points stratégiques (écoles et espaces verts).');

-- Questions : Violesi - San Baquis (Q1 avec image)
INSERT INTO quartier_questions (quartier_id, question_number, question_text, question_image_url) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'violesiroussin'), 1, 'Les quartiers de Violesi et Montaury sont prévus, par le plan local d''urbanisme intercommunal approuvé par la municipalité sortante, pour accueillir 1200 nouveaux logements. C''est largement supérieur aux obligations de constructions de logements sociaux, qui se montent à 760 logements, répartis sur de nombreuses années. Aussi, parce que la RD8n est déjà bien trop saturée, nous estimons que le PLUi doit être revu pour sanctuariser le lit du vallat de Violesi afin d''y créer un véritable parc arboré enjambant le cours d''eau.', 'https://morateur2026.fr/images/violesi.png');
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'violesiroussin'), 2, 'L''avenue André Roussin est à l''abandon. Nous proposons un plan en 2 étapes : tout d''abord, la sécurisation immédiate des traversées avec des feux asservis sur 2 emplacements. Ensuite, le lancement de la déclaration d''utilité publique pour initier le projet de réfection de la chaussée et de création d''un trottoir, en prévoyant les réseaux humides là où ils manquent, qui pourra être achevé avant la fin du mandat.'),
  ((SELECT id FROM quartiers WHERE slug = 'violesiroussin'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?'),
  ((SELECT id FROM quartiers WHERE slug = 'violesiroussin'), 4, 'La lutte contre la prolifération des moustiques dans le quartier passe par le traitement des berges du vallat chaque printemps, et par la pose et la maintenance de bornes aspirateurs à moustiques autour des points stratégiques. De plus, nous proposerons un tarif négocié pour les bornes aspirateurs à moustiques à installer chez soi.');

-- Questions : Centre Ville
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'centreville'), 1, 'Le dernier terrain libre du centre ville est voué, d''après le plan local d''urbanisme approuvé par la municipalité sortante, à être entièrement urbanisé par un mix de logements en étages (jusqu''à 3 étages) et de commerces et services en rez-de-chaussée. Nous estimons que cet espace doit au contraire accueillir une vingtaine de logements tout au plus, et un parc-relais pour les véhicules, permettant le stationnement et facilitant le covoiturage. Quelle orientation préférez-vous ?'),
  ((SELECT id FROM quartiers WHERE slug = 'centreville'), 2, 'Nous souhaitons d''une part revitaliser l''attractivité du village en proposant à des jeunes entreprises de l''artisanat de bouche (chocolatier, glacier, salon de thés...) d''être hébergées dans un des locaux vides du village, assorti d''une autorisation de terrasse. D''autre part, nous vous proposons de remodeler la place Jean Moulin, en construisant à la place de l''ancien Saint-Géran un immeuble de bureau accueillant en rez-de-chaussée un véritable boulanger, avec un fournil. Qu''en pensez-vous ?'),
  ((SELECT id FROM quartiers WHERE slug = 'centreville'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?');

-- Questions : Les Revenants
INSERT INTO quartier_questions (quartier_id, question_number, question_text) VALUES
  ((SELECT id FROM quartiers WHERE slug = 'revenants'), 1, 'La circulation automobile asphyxie notre commune. Et, à courte échéance puisqu''il est prévu dans l''orientation d''aménagement programmée de San Banquis actuellement à l''étape de l''évaluation environnementale préfectorale, il est prévu qu''un demi-échangeur déboule de l''A51 au niveau de la Croix d''Or. Objectif affiché : reporter du trafic depuis les 2 sorties adjacentes des Chabauds et des Trois Pigeons. C''est une conséquence directe de la politique d''urbanisme : il est évident qu''avec les 600 logements en cours d''instruction à Violesi et les 350 à la Malle, la partie sud de la RD8n doit être soulagée. Cependant, cela rabatrait aussi une partie du flux des Trois Pigeons vers la zone des Milles, annulant par avance toute amélioration qui pourrait être obtenue dans la gestion de ce giratoire traversé par la limite communale entre Bouc et Aix. De plus, dans une partie nord de la RD8n plus embouteillée que jamais, le chemin des Revenants deviendrait encore bien davantage qu''aujourd''hui une voie de délestage pour les automobilistes pressés. Aussi, d''après vous, que devons-nous prioriser dans ce dossier ?'),
  ((SELECT id FROM quartiers WHERE slug = 'revenants'), 2, 'Un mur anti-bruit a été érigé il y a maintenant deux décennies du côté des Ormeaux (à droite en roulant vers Aix). Les Revenants étant le quartier le plus exposé au bruit à Bouc-Bel-Air, nous souhaitons créer un tel mur anti-bruit de l''autre côté.'),
  ((SELECT id FROM quartiers WHERE slug = 'revenants'), 3, 'La création de réseaux 5G propres à la mairie permet d''envisager aujourd''hui la pose de caméras et de capteurs de bruit (afin d''intervenir pour les troubles à la tranquillité) et de qualité de l''air (pour vérifier que les seuils imposés par la règlementation sont bien respectés) pour un coût divisé par dix par rapport à 2020. Aussi, l''éclairage public pourra être déclenché par des capteurs de présence. Pensez-vous que ce déploiement soit une priorité pour le prochain mandat ?');
